the reason it failed was that docker was not running now testing again 